name: iOS starter workflow 1            
on:        
  push:     
    branches:    
      - main             
  pull_request: 
    branches: 
      - main 
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
jobs:
  build: 
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Install the Apple certificate and provisioning profile
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          security import certificate.p12 -k ~/Library/Keychains/login.keychain -p pass:$P12_PASSWORD
          security add-provisioning-profile DemoTest.mobileprovision

      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Copy Podfile
        run: cp -r SignIn/Podfile .

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -v '1.11.2'
          pod repo list
          pod setup

      - name: Install dependencies
        run: pod install --project-directory=SignIn/

      - name: Check current directory
        run: |
          pwd
          ls -al

      - name: Navigate to SignIn folder
        run: |
          cd SignIn/
          ls

      - name: Update provisioning profile specifier in Xcode project
        run: |
          gem install xcodeproj
          ruby - <<EOF
          require 'xcodeproj'

          # Define the path to your Xcode project
          project_path = 'SignIn/SignIn.xcodeproj'

          # Define the target name
          target_name = 'SignIn'

          # Define the provisioning profile specifier
          provisioning_profile_specifier = "DemoTest"

          # Open the Xcode project
          project = Xcodeproj::Project.open(project_path)

          # Find the target
          target = project.targets.find { |t| t.name == target_name }

          # Update the provisioning profile settings
          target.build_configuration_list.build_configurations.each do |configuration|
            configuration.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = provisioning_profile_specifier
          end

          # Save the changes to the Xcode project file
          project.save
          EOF
          
      - name: Build
        id: build_ipa
        run: |
          xcodebuild archive \
            -workspace SignIn.xcworkspace \
            -scheme SignIn \
            -configuration Release \
            -archivePath ./build/SignIn.ipa
